name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync LeetCode
        uses: jaywcjlove/leetcode-sync@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
